### ISSUE TITLE
Optimization leads to different output hashes on macos and linux

### ISSUE THREAD

**Issue by avdv** [zaninime/sbt-derivation#14]
I am using the `tar+zstd` archival strategy. The resulting tar files differ on macos and e.g. ubuntu:
```
│ │ -lrwxr-xr-x   0        0        0        0 1980-01-01 00:00:00.000000 ./.coursier/https/repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.12/1.7.1/zinc-persist_2.12-1.7.1.jar -> ../../../../../../../../.boot/scala-2.12.16/org.scala-sbt/sbt/1.7.1/zinc-persist_2.12-1.7.1.jar
│ │ +lrwxrwxrwx   0        0        0        0 1980-01-01 00:00:00.000000 ./.coursier/https/repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.12/1.7.1/zinc-persist_2.12-1.7.1.jar -> ../../../../../../../../.boot/scala-2.12.16/org.scala-sbt/sbt/1.7.1/zinc-persist_2.12-1.7.1.jar
```
Note, the permissions for the links are `lrwxr-xr-x` on macos, but `lrwxrwxrwx` on linux.

**Comment by zaninime** [comment]
Symlinks don't have permissions, so the difference is most likely somewhere else. Can you try without zstd and see if the difference is still there? Zstd is known to be problematic cross-version and cross-systems.

**Comment by avdv** [comment]
Seems like on macos, symlinks also can have permissions, the `chmod` command has a `-h` option to that effect:
```
-h If the file is a symbolic link, change the mode of the link itself rather than the file that the link points to.
```

**Comment by avdv** [comment]
Confirming, after setting `depsOptimize = false` the output hash was the same on maos and ubuntu.

**Comment by zaninime** [comment]
Good finding, my first guess would be to try letting `rdfind` apply 0777 to symlinks also on Mac, however I don't know if there are unintended consequences in doing so.

As soon as I have access to a Mac I can test out if adding `umask 0000` before rdfind (and resetting it afterwards) could solve this issue. Also, it might be the `symlinks` utility that causes this.

The alternative would be adding a note in the README about this known behaviour.

Do you have any suggestions?

**Comment by avdv** [comment]
Hi!

I made a few experiments with some approaches:

1. use umask
2. try to find symlinks with "unusual" permissions and fix them
3. use hardlinks instead of symlinks

Initially, I made the project run on macos-latest too: https://github.com/zaninime/sbt-derivation/compare/master...avdv:sbt-derivation:master

(latest run: https://github.com/avdv/sbt-derivation/actions/runs/3400779662)

# hardlinks

Changes:
https://github.com/avdv/sbt-derivation/compare/master...hardlinks

Project PR:
https://github.com/avdv/scalals/pull/158

Output:
```
Now scanning "/build/tmp.U3sEOfjHPS/project/.sbtboot", found 1 files.
Now scanning "/build/tmp.U3sEOfjHPS/project/.boot", found 88 files.
Now scanning "/build/tmp.U3sEOfjHPS/project/.ivy", found 0 files.
Now scanning "/build/tmp.U3sEOfjHPS/project/.coursier", found 1374 files.
Now have 1463 files in total.
Removed 0 files due to nonunique device and inode.
Total size is 222108949 bytes or 212 MiB
Removed 239 files due to unique sizes from list. 1224 files left.
Now eliminating candidates based on first bytes: removed 1031 files from list. 193 files left.
Now eliminating candidates based on last bytes: removed 8 files from list. 185 files left.
Now eliminating candidates based on sha1 checksum: removed 10 files from list. 175 files left.
It seems like you have 175 files that are not unique
Totally, 78 MiB can be reduced.
Now making hard links.
Making 88 links.
```

With `depsOptimize = false`, my dependencies would take up 184 MB, with `depsOptimize = true` the file size was reduced to 126MB.

# fix symlinks

https://github.com/avdv/sbt-derivation/compare/master...fix-perms

This approach was not successful and I stopped trying. It fails because the `chmod` command inside the nix build is not the native one from darwin and thus does not support the `-h` switch.

# umask

Changes:
https://github.com/avdv/sbt-derivation/compare/master...umask

Project PR:
https://github.com/avdv/scalals/pull/159

Same size reduction as with the hardlink approach.
 
----

Overall, using hardlinks is an easy solution that fixed the problem at hand, but I suppose it would not take care of symlinks modified / created by the `symlinks` utility. Neither approach would take care of pre-existing symlinks with "unusual" permissions.

**Comment by zaninime** [comment]
Sorry for the long delay and thanks for running those tests, I appreciate the time you put into this.

One thing worth adding to the discussion is that there are no symlinks created by sbt during the execution. While it _could_ happen that some symlink is created, today this doesn't happen and I think we should take this for good.

1. By going with hardlinks we would remove the dependency on `symlinks` altogether, as it was put in place to fix the symlinks created by `rdfind`. The symlinks are born as absolute and need to be turned into relative to avoid writing absolute paths in the TAR archive.
2. Using `umask` would fix the issue as you pointed out, although we now are chaining three operations for an unusual/unexpected (is it even?) behaviour of `rdfind` across OSes.

I find the symlinks approach to be slightly better as there seem to be some complications around the behaviour of `rdfind` when asked to create hardlinks (https://github.com/pauldreik/rdfind/issues/75 + README). It might be worth trying also [fclones](https://search.nixos.org/packages?show=fclones&from=0&size=50&sort=relevance&type=packages&query=fclones) to see if that aids the situation.

Other than that, I find both approaches to be pretty equivalent, so it makes sense to focus on whether the combination of sbt and any project relying on sbt-derivation would work "better" either with symlinks or with hardlinks.

It would seem a safer choice to go with symlinks due to their nature of being independent of the underlying storage, however the main shortcoming of hardlinks (needing the colocated on the same FS) seems irrelevant for this case.

As a last resort, I'm considering adding a note on the README to link to this issue and recommend disabling the optimization when working cross-OS (or using separate hashes, FWIW).
