### ISSUE TITLE
`depsSha256` vs including only build files

### ISSUE THREAD

**Issue by kubukoz** [zaninime/sbt-derivation#6]
Hi! I was curious why the approach chosen was to use `depsSha256` (which is a bit error prone, as you could change the build and not notice the sha changes until you try to rebuild on a different machine, thus having a non-deterministic build). Another alternative I've considered is to change the input `src` of the deps derivation to something like

- all `.sbt` files in the source directory, and
- everything in `project/` that's not in a `target` directory.

This is pretty much all you need to prepare dependencies for an sbt project, so if these were the only inputs, and there was no "fixed output derivation", we could guarantee the deps will be rebuilt iff one of the build-related files changes.

This would eliminate the need to have the sha altogether - I think that'd be a better user experience for pragmatic usage (people usually don't use snapshots or repositories with mutable packages). Maybe not as a default or only option, but as an alternative to the current approach?

**Comment by kubukoz** [comment]
Also wanted to note I'm aware it's possible to override the `src` attribute for deps, but _I think_ there's no way to remove the attributes specifying the fixed-output (`outputHashMode`, `outputHashAlgo`) - I'd love to be proven wrong though.

**Comment by kubukoz** [comment]
Ran `nix-build --check` on a simple project with both ways: fixed output vs nulls. Both give me

`derivation '/nix/store/7hl2wa8nv9vfngr09lw26q4nj6xm0qj2-sbt-nix-demo-1.0.0.drv' may not be deterministic: output '/nix/store/9vv651y34z95rzf8yf7kahbrxz8d18xx-sbt-nix-demo-1.0.0' differs`.

**Comment by kubukoz** [comment]
Not sure. If only the deps phase can access the network, how would you solve e.g. codegen based on external sources? e.g. Caliban's codegen allows you to pass a path to a GraphQL spec. Would a user need to guarantee immutability by fetching it themselves, e.g. into a file (or with fetchurl/whatever), and passing that to sbt, instead of the sbt plugin doing it in the compilation step? (the results would be codegen'd to `target`, not one of the global sbt paths, so it wouldn't be part of the first derivation's output)

**Comment by zaninime** [comment]
That is correct. You have to find a way to fetch that file at some point. You can do it before running a nix build, or as part of it via `fetchurl` or whatever else fits you, but it's outside the scope of this project.

**Comment by zaninime** [comment]
Hi @chriswarbo and thanks for the extended post! This could indeed be a way to proceed. The way I see it, is to have this as a complementary part to what currently this project is.

As the README says, the current usage is similar to:

```nix
sbt.mkDerivation {
  pname = "whatever-you-like";
  # ...
}
```

Nothing would prevent anyone from doing:

```nix
sbt.mkDerivation {
  pname = "whatever-you-like";
  overrideDepsAttrs = (old: {
    pname = "${old.pname}-${hashFromSomewhere}";
  });
  # ...
}
```

Of course it would be much nicer to have, ie:

```nix
sbt.mkDerivation {
  pname = "whatever-you-like";
  depsHashedName.enable = true;
}
```

The question is we can go as far as saying this is the new, "recommended" approach.

Is your idea implemented in any other language support framework in Nix? I'm looking at Rust, Go, ... And if not, why.

**Comment by chriswarbo** [comment]
Hi @zaninime

> Is your idea implemented in any other language support framework in Nix? I'm looking at Rust, Go, ... And if not, why.

I don't think so. I think Nixpkgs generally tries to avoid import-from-derivation, since it causes building to happen at eval time. That's not too bad when the config files already exists, e.g. if `foo.nix` contains `sbt.mkDerivation { src = ./.; ... }` then that `./.` directory must already exist (either outside the Nix store, or as a derivation that's already been built) since it contains the `foo.nix` file being evaluated! However, consider something like the following:

```nix
sbt.mkDerivation {
  pname = "my-project";
  depsHashedName.enable = true;
  src = nixpkgs.runCommand "my-project-src" { inherit my-arbitrary-dependencies; } ''
    my-arbitrary-commands "$out"
  '';
}
```

Evaluating this to get the `my-project.drv` file requires making the deps .drv file too, and that file's name depends on the hash of the *output* from that `runCommand`. That requires an unbounded amount of work, which can make evaluation slow and is especially annoying when using Hydra.

> The question is we can go as far as saying this is the new, "recommended" approach.

It's probably not a good idea to hard-code one approach (e.g. with a toggle like `depsHashedName = true;`); there are too many considerations which may vary between users and projects.

For example, the approach I showed above will cause rebuilding if *anything* about the config changes; in particular, changing the version would cause the dependencies to rebuild, which undermines the existing `versionInDepsName ? false;` option. The above implementation also makes multiple copies of the config files (once to put them in the Nix store, and again when making the temporary .tar file to hash), which may be undesirable for some.

A more-precise alternative could pull out the dependency info and hash that, but doing so would require a more heavyweight tool (e.g. SBT itself, or some sort of Scala/SBT parsing tool); that would make the hashing slower, which may be undesirable for some. And so on.

I think an option like `overrideDepsAttrs ? (_: {})` would be useful, certainly for my use-cases. The rest could probably just live in documentation :)
